### ISSUE TITLE
How to enable saving commands?

### ISSUE THREAD

**Issue by trusktr** [weechatter/weechat-scripts#14]
I was looking at /histman output, and it says to try using /autosetbuffer, which results in

```
Error: unknown command "/autosetbuffer"
```

**Comment by trusktr** [comment]
Ok, nevermind, I see the buffer_autoset.py script is needed.

**Comment by trusktr** [comment]
Mind helping me understand what `o save and restore "global" command history, use option "save_global".` means?

How would I `use option "save_global"`?

**Comment by trusktr** [comment]
I tried `/set weechat.save_global on` but that didn't work. hmmm....

**Comment by trusktr** [comment]
`plugins.var.python.histman.save_global`. Never would I ever have guessed. The iset script helped me discover it.

**Comment by trusktr** [comment]
I can't get it to work. Maybe I don't understand. I set `plugins.var.python.histman.save_global` to "command", then I try some commands, and finally `/quit`, then the next time I start weechat I try `/history` and it's empty. Is that what I should expect?

**Comment by Purgator** [comment]
Hello,

did you get it to work ?
I'm interested.

Regards.

**Comment by weechatter** [comment]
I think i have to rewrite some part, because rmodifier is not used anymore in weechat. I'll have a look

**Comment by Purgator** [comment]
Nice thank you =) I will watch out

**Comment by archenemies** [comment]
So there is currently no way to save command history in weechat? This is very confusing for a new user, I thought it would be a feature enabled by default and not something that requires downloading multiple plugins all lacking adequate documentation.

**Comment by weechatter** [comment]
script != plugins in weechat @archenemies 

nearly every command, option, script, plugin has an /help text.

script fixed: https://github.com/weechatter/weechat-scripts/blob/master/python/histman.py
